_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
accelerator:
    value: auto
adversarial_mixing:
    value: true
batch_size:
    value: 256
check_val_every_n_epoch:
    value: null
datasplitter_kwargs:
    value: null
devices:
    value: auto
early_stopping:
    value: true
early_stopping_patience:
    value: 10
eps:
    value: 1e-08
expression_architecture:
    value: linear
figure_output_dir:
    value: /gpfs/commons/home/kisaev/multi_vi_splice_runs/MultiVISpliceTraining_20250616_154811_job5162658/figures
gradient_clipping:
    value: true
gradient_clipping_max_norm:
    value: 5
lr:
    value: 1e-05
lr_factor:
    value: 0.5
lr_patience:
    value: 30
lr_scheduler_metric:
    value: elbo_validation
lr_scheduler_type:
    value: step
lr_threshold:
    value: 0
max_epochs:
    value: 75
modality_weights:
    value: equal
model_save_dir:
    value: /gpfs/commons/home/kisaev/multi_vi_splice_runs/MultiVISpliceTraining_20250616_154811_job5162658/models
mudata_path:
    value: /gpfs/commons/groups/knowles_lab/Karin/Leaflet-analysis-WD/MOUSE_SPLICING_FOUNDATION/MODEL_INPUT/052025/SUBSETTOP5CELLSTYPES_aligned__ge_splice_combined_20250513_035938_full_genes.h5mu
n_epochs_kl_warmup:
    value: 30
n_latent:
    value: 20
n_steps_kl_warmup:
    value: null
plan_kwargs:
    value: null
reduce_lr_on_plateau:
    value: false
save_best:
    value: true
shuffle_set_split:
    value: true
splicing_architecture:
    value: partial
splicing_loss_type:
    value: dirichlet_multinomial
step_size:
    value: 20
train_size:
    value: null
umap_cell_label:
    value:
        - broad_cell_type
        - dataset
validation_size:
    value: null
weight_decay:
    value: 1e-06
