_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
accelerator:
    value: auto
adata_path:
    value: /gpfs/commons/groups/knowles_lab/Karin/Leaflet-analysis-WD/MOUSE_SPLICING_FOUNDATION/MODEL_INPUT/052025/train_70_30_ge_splice_combined_20250513_035938.h5mu
batch_size:
    value: 256
check_val_every_n_epoch:
    value: null
code_dim:
    value: 32
datasplitter_kwargs:
    value: null
deeply_inject_covariates:
    value: true
devices:
    value: auto
dropout_rate:
    value: 0.01
early_stopping:
    value: true
encode_covariates:
    value: false
encoder_hidden_dim:
    value: 128
eps:
    value: 1e-08
fig_dir:
    value: /gpfs/commons/home/svaidyanathan/splice_vi_partial_vae_runs/SpliceVI_PartialVAE_Training_20250630_185931_job5450236/figures
h_hidden_dim:
    value: 64
initialize_embeddings_from_pca:
    value: true
latent_dim:
    value: 10
learn_concentration:
    value: true
lr:
    value: 1e-05
lr_factor:
    value: 0.6
lr_min:
    value: 0
lr_patience:
    value: 30
lr_threshold:
    value: 0
max_epochs:
    value: 2000
model_dir:
    value: /gpfs/commons/home/svaidyanathan/splice_vi_partial_vae_runs/SpliceVI_PartialVAE_Training_20250630_185931_job5450236/models
n_epochs_kl_warmup:
    value: 50
n_steps_kl_warmup:
    value: null
plan_kwargs:
    value: null
reduce_lr_on_plateau:
    value: false
save_best:
    value: true
shuffle_set_split:
    value: true
splice_likelihood:
    value: dirichlet_multinomial
train_size:
    value: null
umap_colors:
    value:
        - cell_type_grouped
use_transformer:
    value: false
validation_size:
    value: null
weight_decay:
    value: 0.001
